# Generated by Django 6.0.2 on 2026-03-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('aguardando_analise', 'Aguardando análise'), ('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('aguardando_teceiros', 'Aguardando terceiros'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='aguardando_analise', max_length=25)),
                ('priority', models.TextField(choices=[('indefinida', 'Indefinida'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='indefinida', max_length=15)),
            ],
        ),
    ]
